repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest compatible version
    hooks:
      - id: trailing-whitespace
        exclude: .ipynb
      - id: end-of-file-fixer
        exclude: .ipynb
      - id: check-added-large-files
        exclude: .ipynb

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        exclude: \.ipynb$

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: \.ipynb$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        exclude: \.ipynb

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
        exclude: \.ipynb$
