

in_agent_filepath: null
out_agent_filepath: "./models/dqn_3cov_lstm_1k.pth"
out_results_filepath: "./models/dqn_3cov_lstm_1k.csv"

train_play_game_settings:
  episodes: 1000
  frame_stack_size: 4
  frame_skip: 1
  room: "StreetFighterIISpecialChampionEdition-Genesis"
  render_mode: "rgb_array"
  record: "./replays/train/"


agent_settings:
  action_dim: 576
  state_shape: !!python/tuple [4, 96, 96]
  gamma: 0.99
  lr: 0.01
  epsilon_start: 0.0
  epsilon_end: 0.0
  epsilon_decay: 1.0e-6
  target_update_freq: 10_000
  replay_capacity: 150_000
