

in_agent_filepath: null 
out_agent_filepath: "./models/dqn_lstm.pth"

train_play_game_settings:
  episodes: 1000
  frame_stack_size: 4 # must match agent state_shape
  frame_skip: 3
  room: "StreetFighterIISpecialChampionEdition-Genesis"
  render_mode: "rgb_array"
  record: "./recordings_exp01/"


agent_settings:
  action_dim: 20
  state_shape: !!python/tuple [4, 96, 96] # must match frame stack
  gamma: 0.99
  lr: 0.001
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay: 1.0e-6
  target_update_freq: 24_000
  replay_capacity: 45_000
