

in_agent_filepath: "dqn_checkpoint.pth"
out_agent_filepath: "./models/dqn_checkpoint.pth"

train_play_game_settings:
  episodes: 100
  frame_stack_size: 4 # must match agent state_shape
  frame_skip: 3
  room: "StreetFighterIISpecialChampionEdition-Genesis"
  render_mode: "rgb_array"
  record: "./recordings_experiment/"


agent_settings:
  action_dim: 20
  state_shape: !!python/tuple [4, 200, 256] # must match frame stack
  gamma: 0.99
  lr: 0.001
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay: 1.0e-6
  target_update_freq: 24_000
  replay_capacity: 45_000
